Feature/eco 2300/crefopay credit card without 3d secure yves
spryker-eco/crefo-pay pull request #2
Opened 2019-02-20 15:32 UTC by nikita-lysenko

Ticket: https://spryker.atlassian.net/browse/ECO-2504

2019-02-21 08:17 UTC, tolerants requested changes

2019-02-21 08:17 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/molecules/crefopay-form-loader/crefopay-form-loader.ts
> +const CREFOPAY_CONFIG = {
`CREFOPAY_CONFIG` -> `CREFO_PAY_CONFIG`.

2019-02-21 08:17 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/molecules/crefopay-form-loader/crefopay-form-loader.ts
> +    protected secureFieldsClientInstance: any;
`secureFieldsClientInstance` -> `secureFieldsClient`.

2019-02-21 08:17 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/molecules/crefopay-form-loader/crefopay-form-loader.ts
> +            // Successful registration, continue to next page using JavaScript
And why you do nothing on success?

2019-02-21 08:17 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/molecules/crefopay-form-loader/crefopay-form-loader.ts
> +            // Error during registration, check the response for more details and dynamically show a message for the customer
And who should implement error handling? Please show error message and error details.

2019-02-21 08:17 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/molecules/crefopay-form-loader/crefopay-form-loader.ts
> +            // Successful registration, continue to next page using JavaScript
`Successful registration` - why registration? This is initializationComplete callback.

2019-02-21 08:17 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/molecules/crefopay-form-loader/crefopay-form-loader.ts
> +            // Error during registration, check the response for more details and dynamically show a message for the customer
The same - please implement error handling.

2019-02-21 08:17 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/molecules/crefopay-form-loader/crefopay-form-loader.twig
> +    shopPublicKey: '',
Why do you need that data? If you can only leave only attribute.

2019-02-21 08:17 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/molecules/crefopay-form-loader/crefopay-form-loader.twig
> +    orderId: ''
The same.

2019-02-21 08:17 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/molecules/crefopay-form-loader/crefopay-form-loader.twig
> +    shopPublicKey: '',
The only reason I see - to make it required. And as I see it should be required.

2019-02-21 08:17 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/views/credit-card-3d/credit-card-3d.twig
> +                <label><input type="radio" data-crefopay="paymentMethod" value="CC">Creditcard</label><br>
Please remove `<br>`.

2019-02-21 08:17 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/views/credit-card-3d/credit-card-3d.twig
> +                <span>Accountholder: </span>
Why you are mixing inline and block elements? Please fix markup.

2019-02-21 08:17 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/views/credit-card-3d/credit-card-3d.twig
> +                <label><input type="radio" data-crefopay="paymentMethod" value="CC">Creditcard</label><br>
Please add translation. Check it everywhere.

2019-02-21 08:17 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/views/direct-debit/direct-debit.twig
> +    {% block requestForm %}
Wrong indention here and below.

2019-03-04 07:56 UTC, tolerants requested changes

2019-03-04 07:56 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/molecules/crefopay-form-loader/crefopay-form-loader.ts
> +    public secureFieldsClient: any;
Why public? Also suggest to rename, bcs it's confusing we have vendor method and our class property with the same name.

2019-03-04 07:56 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/molecules/crefopay-form-loader/crefopay-form-loader.twig
> +    {% set crefoPayConfig = {
It should be a part of data contract.

2019-03-04 07:56 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/molecules/crefopay-form-loader/crefopay-form-loader.twig
> +    'crefo-pay-config': data.secureFieldsPlaceholders ? crefoPayConfig | json_encode() : '',
But if we don't have `secureFieldsPlaceholders` then it looks like we don't need to run our js.

2019-03-04 07:56 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/molecules/crefopay-form-loader/crefopay-form-loader.twig
> +    name: 'crefopay-form-loader',
Please rename `crefopay-form-loader` -> `crefopay-payment-from`.

2019-03-04 07:56 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/molecules/crefopay-form-loader/crefopay-form-loader.twig
> +            {{ 'All fields are required.' | trans }}
Why not in glossary?

2019-03-04 07:56 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/views/credit-card-3d/credit-card-3d.twig
> +            form: data.form,
How is it working? In `crefopay-form-loader` we have 5 required fields, but you are using just 4 here.

2019-03-04 07:56 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/views/direct-debit/direct-debit.twig
> +                <label><input type="radio" data-crefopay="paymentInstrument.id" value="Aqc9O5SSJuQTDHC9KXFE0Q" class="spacing-right">Registered bank account (IBAN: DE12 3456 7890 1112 1314)</label>
Why not translated?

2019-03-04 12:29 UTC, nikita-lysenko commented on src/SprykerEco/Yves/CrefoPay/Theme/default/views/credit-card-3d/credit-card-3d.twig
> +            form: data.form,
it's just placeholders for further implementation, fixed for current state

2019-03-04 12:31 UTC, nikita-lysenko commented on src/SprykerEco/Yves/CrefoPay/Theme/default/views/direct-debit/direct-debit.twig
> +                <label><input type="radio" data-crefopay="paymentInstrument.id" value="Aqc9O5SSJuQTDHC9KXFE0Q" class="spacing-right">Registered bank account (IBAN: DE12 3456 7890 1112 1314)</label>
added translation in macro at line 10-11

2019-03-13 12:33 UTC, tolerants requested changes

2019-03-13 12:33 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/atoms/crefopay-checkbox-helper/crefopay-checkbox-helper.ts
> +    protected applyAttributes (): void {
Please remove space before `()`.

2019-03-13 12:33 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/atoms/crefopay-checkbox-helper/crefopay-checkbox-helper.ts
> +        let jointContainer = (<HTMLElement>triggered).closest(this.jointContainerSelector);
`let` -> `const`.

2019-03-13 12:33 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/atoms/crefopay-checkbox-helper/crefopay-checkbox-helper.ts
> +        let triggeredTarget: HTMLInputElement = jointContainer.querySelector(this.targetSelector);
`let` -> `const`.

2019-03-13 12:33 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/atoms/crefopay-checkbox-helper/crefopay-checkbox-helper.ts
> +        this.targets.forEach((target: HTMLInputElement)=>{
Wrap `=>` with spaces.

2019-03-13 12:33 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/atoms/crefopay-checkbox-helper/crefopay-checkbox-helper.ts
> +        this.targets.forEach((target: HTMLInputElement)=>{
Wrap `=>` with spaces.

2019-03-13 12:33 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/atoms/crefopay-checkbox-helper/crefopay-checkbox-helper.ts
> +    get customAttrName() {
`customAttrName` -> `customAttributeName`.

2019-03-13 12:33 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/atoms/crefopay-checkbox-helper/crefopay-checkbox-helper.ts
> +        return this.getAttribute('custom-attr-name');
`custom-attr-name` -> `custom-attribute-name`.

2019-03-13 12:33 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/atoms/crefopay-checkbox-helper/crefopay-checkbox-helper.ts
> +    get customAttrValue() {
`customAttrValue` -> `customAttributeValue`.

2019-03-13 12:33 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/atoms/crefopay-checkbox-helper/crefopay-checkbox-helper.ts
> +        return this.getAttribute('custom-attr-value');
`custom-attr-value` -> `custom-attribute-value`.

2019-03-13 12:33 UTC, tolerants commented on src/SprykerEco/Yves/CrefoPay/Theme/default/components/atoms/crefopay-checkbox-helper/crefopay-checkbox-helper.ts
> +    protected syncCheckboxes(triggered: EventTarget): void {
Why the name is `syncCheckboxes`? It is working only with one checkbox. And it not syncs but makes it checked. Suggest to rename into `checkCheckbox`.
`triggered`-> `checkbox`.

2019-03-13 13:11 UTC, tolerants approved these changes

2019-03-13 13:15 UTC, lockw1n approved these changes
Changes were tested.

2019-03-13 13:15 UTC, merged